# Generated by Django 5.0.6 on 2024-09-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Car', 'Car'), ('Truck', 'Truck'), ('SUV', 'SUV')], max_length=50)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('first_registration', models.CharField(max_length=10)),
                ('mileage', models.CharField(max_length=20)),
                ('fuel', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], max_length=20)),
                ('engine_size', models.CharField(max_length=20)),
                ('power', models.CharField(max_length=20)),
                ('gearbox', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=20)),
                ('num_seats', models.CharField(max_length=5)),
                ('doors', models.CharField(max_length=5)),
                ('color', models.CharField(max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
